name: ml-for-spectro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - h5py
  - jupyterlab
  - ipykernel
  - plotly
  - pyside6
  - pyqt  # for GUI support with PySide6 tools
  - seaborn
  - tqdm
  - pip
  - pip:
      - tensorflow-macos
      - tensorflow-metal
